/*
SELECT 'DROP TABLE ' + SCHEMA_NAME(schema_id) +'.' + NAME  FROM SYS.objects
WHERE TYPE = 'U' AND SCHEMA_NAME(schema_id) = 'LOS_GESTORES'
ORDER BY create_date DESC
*/
DROP TABLE LOS_GESTORES.Detalle_Compra
DROP TABLE LOS_GESTORES.Compra
DROP TABLE LOS_GESTORES.Detalle_Factura
DROP TABLE LOS_GESTORES.Envio
DROP TABLE LOS_GESTORES.Proveedor
DROP TABLE LOS_GESTORES.Detalle_Pedido
DROP TABLE LOS_GESTORES.Factura
DROP TABLE LOS_GESTORES.Pedido
DROP TABLE LOS_GESTORES.Sillon
DROP TABLE LOS_GESTORES.Cliente
DROP TABLE LOS_GESTORES.Sillon_Medida
DROP TABLE LOS_GESTORES.Sillon_Modelo
DROP TABLE LOS_GESTORES.Tela
DROP TABLE LOS_GESTORES.Relleno
DROP TABLE LOS_GESTORES.Sucursal
DROP TABLE LOS_GESTORES.Madera
DROP TABLE LOS_GESTORES.Localidad
DROP TABLE LOS_GESTORES.Provincia





