/*
SELECT 'DROP PROCEDURE ' + SCHEMA_NAME(schema_id) +'.' + NAME FROM SYS.objects
WHERE TYPE = 'P' AND SCHEMA_NAME(schema_id) = 'LOS_GESTORES'
ORDER BY create_date DESC
*/

DROP PROCEDURE LOS_GESTORES.SP_ENVIO
DROP PROCEDURE LOS_GESTORES.SP_FACTURA
DROP PROCEDURE LOS_GESTORES.SP_DETALLE_PEDIDO
DROP PROCEDURE LOS_GESTORES.SP_PEDIDO
DROP PROCEDURE LOS_GESTORES.SP_CLIENTE
DROP PROCEDURE LOS_GESTORES.SP_DETALLE_COMPRA
DROP PROCEDURE LOS_GESTORES.SP_COMPRA
DROP PROCEDURE LOS_GESTORES.SP_PROVEEDOR
DROP PROCEDURE LOS_GESTORES.SP_SILLON
DROP PROCEDURE LOS_GESTORES.SP_SILLON_MODELO
DROP PROCEDURE LOS_GESTORES.SP_SILLON_MEDIDA
DROP PROCEDURE LOS_GESTORES.SP_RELLENO
DROP PROCEDURE LOS_GESTORES.SP_MADERA
DROP PROCEDURE LOS_GESTORES.SP_TELA
DROP PROCEDURE LOS_GESTORES.SP_SUCURSAL
DROP PROCEDURE LOS_GESTORES.SP_LOCALIDAD
DROP PROCEDURE LOS_GESTORES.SP_PROVINCIA