--SELECT 'DROP PROCEDURE ' + SCHEMA_NAME(schema_id) +'.' + NAME FROM SYS.objects
--WHERE TYPE = 'P' AND SCHEMA_NAME(schema_id) = 'LOS_GESTORES'
--ORDER BY OBJECT_ID DESC

drop procedure LOS_GESTORES.SP_CLIENTE;
drop procedure LOS_GESTORES.SP_DETALLE_COMPRA;
drop procedure LOS_GESTORES.SP_DETALLE_FACTURA;
drop procedure LOS_GESTORES.SP_DETALLE_PEDIDO;
drop procedure LOS_GESTORES.SP_ENVIO;
drop procedure LOS_GESTORES.SP_FACTURA;
drop procedure LOS_GESTORES.SP_LOCALIDAD;
drop procedure LOS_GESTORES.SP_MADERA;
drop procedure LOS_GESTORES.SP_MATERIAL;
drop procedure LOS_GESTORES.SP_PEDIDO;
drop procedure LOS_GESTORES.SP_PROVEEDOR;
drop procedure LOS_GESTORES.SP_PROVINCIA;
drop procedure LOS_GESTORES.SP_RELLENO;
drop procedure LOS_GESTORES.SP_SILLON;
drop procedure LOS_GESTORES.SP_SILLON_MEDIDA;
drop procedure LOS_GESTORES.SP_SILLON_MODELO;