/*
SELECT 'EXEC ' + SCHEMA_NAME(schema_id) +'.' + NAME + CHAR(13) + ' GO'  FROM  SYS.objects
 WHERE TYPE = 'P' AND SCHEMA_NAME(schema_id) = 'LOS_GESTORES'
 ORDER BY create_date 
*/

EXEC LOS_GESTORES.SP_PROVINCIA
eXEC LOS_GESTORES.SP_LOCALIDAD
 
EXEC LOS_GESTORES.SP_SUCURSAL

EXEC LOS_GESTORES.SP_MADERA
EXEC LOS_GESTORES.SP_TELA
EXEC LOS_GESTORES.SP_RELLENO

EXEC LOS_GESTORES.SP_SILLON_MEDIDA
EXEC LOS_GESTORES.SP_SILLON_MODELO

EXEC LOS_GESTORES.SP_SILLON



EXEC LOS_GESTORES.SP_CLIENTE




 GO
EXEC LOS_GESTORES.SP_COMPRA
 GO

 GO
 GO
EXEC LOS_GESTORES.SP_PROVEEDOR
 GO
EXEC LOS_GESTORES.SP_SUCURSAL



