
-- SELECT 'EXEC ' + SCHEMA_NAME(schema_id) +'.' + NAME + CHAR(13) + ' GO'  FROM  SYS.objects
-- WHERE TYPE = 'P' AND SCHEMA_NAME(schema_id) = 'LOS_GESTORES'
-- ORDER BY OBJECT_ID DESC



EXEC LOS_GESTORES.SP_PROVINCIA
 GO
EXEC LOS_GESTORES.SP_LOCALIDAD
 GO
EXEC LOS_GESTORES.SP_CLIENTE
 GO
EXEC LOS_GESTORES.SP_SUCURSAL
 GO
EXEC LOS_GESTORES.SP_PROVEEDOR
 GO

EXEC LOS_GESTORES.SP_SILLON_MEDIDA
GO


EXEC LOS_GESTORES.SP_COMPRA
 GO
EXEC LOS_GESTORES.SP_RELLENO
 GO