/*
SELECT 'EXEC ' + SCHEMA_NAME(schema_id) +'.' + NAME
-- + CHAR(13) + ' GO'
FROM  SYS.objects
 WHERE TYPE = 'P' AND SCHEMA_NAME(schema_id) = 'LOS_GESTORES'
 ORDER BY create_date 
*/


EXEC LOS_GESTORES.SP_PROVINCIA
EXEC LOS_GESTORES.SP_LOCALIDAD
EXEC LOS_GESTORES.SP_SUCURSAL
EXEC LOS_GESTORES.SP_MADERA
EXEC LOS_GESTORES.SP_TELA
EXEC LOS_GESTORES.SP_RELLENO
EXEC LOS_GESTORES.SP_SILLON_MEDIDA
EXEC LOS_GESTORES.SP_SILLON_MODELO
EXEC LOS_GESTORES.SP_SILLON
EXEC LOS_GESTORES.SP_PROVEEDOR
EXEC LOS_GESTORES.SP_COMPRA
EXEC LOS_GESTORES.SP_DETALLE_COMPRA
EXEC LOS_GESTORES.SP_CLIENTE
EXEC LOS_GESTORES.SP_PEDIDO
EXEC LOS_GESTORES.SP_DETALLE_PEDIDO
EXEC LOS_GESTORES.SP_FACTURA
EXEC LOS_GESTORES.SP_DETALLE_FACTURA
EXEC LOS_GESTORES.SP_ENVIO