/*
SELECT 'TRUNCATE TABLE ' + SCHEMA_NAME(schema_id) +'.' + NAME  FROM SYS.objects
WHERE TYPE = 'U' AND SCHEMA_NAME(schema_id) = 'LOS_GESTORES'
ORDER BY create_date DESC
*/


TRUNCATE TABLE LOS_GESTORES.Compra
TRUNCATE TABLE LOS_GESTORES.Detalle_Compra
TRUNCATE TABLE LOS_GESTORES.Proveedor
TRUNCATE TABLE LOS_GESTORES.Envio
TRUNCATE TABLE LOS_GESTORES.Factura
TRUNCATE TABLE LOS_GESTORES.Detalle_Factura
TRUNCATE TABLE LOS_GESTORES.Detalle_Pedido
TRUNCATE TABLE LOS_GESTORES.Cliente
TRUNCATE TABLE LOS_GESTORES.Pedido
TRUNCATE TABLE LOS_GESTORES.Sillon_Modelo
TRUNCATE TABLE LOS_GESTORES.Sillon
TRUNCATE TABLE LOS_GESTORES.Sillon_Medida
TRUNCATE TABLE LOS_GESTORES.Tela
TRUNCATE TABLE LOS_GESTORES.Relleno
TRUNCATE TABLE LOS_GESTORES.Sucursal
TRUNCATE TABLE LOS_GESTORES.Madera
TRUNCATE TABLE LOS_GESTORES.Localidad
TRUNCATE TABLE LOS_GESTORES.Provincia





