-- Script para eliminar todas las estructuras del esquema LOS_GESTORES

PRINT 'Iniciando la eliminacion de estructuras del esquema LOS_GESTORES...';
GO

-- 1. Eliminar Triggers

PRINT 'Eliminando Triggers';

IF OBJECT_ID('LOS_GESTORES.MATERIAL_AD', 'TR') IS NOT NULL
BEGIN
    DROP TRIGGER LOS_GESTORES.MATERIAL_AD;
    PRINT 'Trigger LOS_GESTORES.MATERIAL_AD eliminado.';
END
GO

-- 2. Eliminar Stored Procedures

PRINT 'Eliminando Stored Procedures';

IF OBJECT_ID('LOS_GESTORES.SP_PROVINCIA', 'P') IS NOT NULL DROP PROCEDURE LOS_GESTORES.SP_PROVINCIA;
IF OBJECT_ID('LOS_GESTORES.SP_LOCALIDAD', 'P') IS NOT NULL DROP PROCEDURE LOS_GESTORES.SP_LOCALIDAD;
IF OBJECT_ID('LOS_GESTORES.SP_SUCURSAL', 'P') IS NOT NULL DROP PROCEDURE LOS_GESTORES.SP_SUCURSAL;
IF OBJECT_ID('LOS_GESTORES.SP_MATERIAL', 'P') IS NOT NULL DROP PROCEDURE LOS_GESTORES.SP_MATERIAL;
IF OBJECT_ID('LOS_GESTORES.SP_MADERA', 'P') IS NOT NULL DROP PROCEDURE LOS_GESTORES.SP_MADERA;
IF OBJECT_ID('LOS_GESTORES.SP_TELA', 'P') IS NOT NULL DROP PROCEDURE LOS_GESTORES.SP_TELA;
IF OBJECT_ID('LOS_GESTORES.SP_RELLENO', 'P') IS NOT NULL DROP PROCEDURE LOS_GESTORES.SP_RELLENO;
IF OBJECT_ID('LOS_GESTORES.SP_SILLON_MEDIDA', 'P') IS NOT NULL DROP PROCEDURE LOS_GESTORES.SP_SILLON_MEDIDA;
IF OBJECT_ID('LOS_GESTORES.SP_SILLON_MODELO', 'P') IS NOT NULL DROP PROCEDURE LOS_GESTORES.SP_SILLON_MODELO;
IF OBJECT_ID('LOS_GESTORES.SP_SILLON', 'P') IS NOT NULL DROP PROCEDURE LOS_GESTORES.SP_SILLON;
IF OBJECT_ID('LOS_GESTORES.SP_PROVEEDOR', 'P') IS NOT NULL DROP PROCEDURE LOS_GESTORES.SP_PROVEEDOR;
IF OBJECT_ID('LOS_GESTORES.SP_COMPRA', 'P') IS NOT NULL DROP PROCEDURE LOS_GESTORES.SP_COMPRA;
IF OBJECT_ID('LOS_GESTORES.SP_DETALLE_COMPRA', 'P') IS NOT NULL DROP PROCEDURE LOS_GESTORES.SP_DETALLE_COMPRA;
IF OBJECT_ID('LOS_GESTORES.SP_CLIENTE', 'P') IS NOT NULL DROP PROCEDURE LOS_GESTORES.SP_CLIENTE;
IF OBJECT_ID('LOS_GESTORES.SP_PEDIDO', 'P') IS NOT NULL DROP PROCEDURE LOS_GESTORES.SP_PEDIDO;
IF OBJECT_ID('LOS_GESTORES.SP_DETALLE_PEDIDO', 'P') IS NOT NULL DROP PROCEDURE LOS_GESTORES.SP_DETALLE_PEDIDO;
IF OBJECT_ID('LOS_GESTORES.SP_FACTURA', 'P') IS NOT NULL DROP PROCEDURE LOS_GESTORES.SP_FACTURA;
IF OBJECT_ID('LOS_GESTORES.SP_DETALLE_FACTURA', 'P') IS NOT NULL DROP PROCEDURE LOS_GESTORES.SP_DETALLE_FACTURA;
IF OBJECT_ID('LOS_GESTORES.SP_ENVIO', 'P') IS NOT NULL DROP PROCEDURE LOS_GESTORES.SP_ENVIO;

PRINT 'Stored Procedures eliminados.';
GO

-- 3. Eliminar Tablas (en orden inverso de dependencia de FKs)

PRINT 'Eliminando Tablas';

IF OBJECT_ID('LOS_GESTORES.Envio', 'U') IS NOT NULL DROP TABLE LOS_GESTORES.Envio;
IF OBJECT_ID('LOS_GESTORES.Detalle_Factura', 'U') IS NOT NULL DROP TABLE LOS_GESTORES.Detalle_Factura;
IF OBJECT_ID('LOS_GESTORES.Detalle_Pedido', 'U') IS NOT NULL DROP TABLE LOS_GESTORES.Detalle_Pedido;
IF OBJECT_ID('LOS_GESTORES.Factura', 'U') IS NOT NULL DROP TABLE LOS_GESTORES.Factura;
IF OBJECT_ID('LOS_GESTORES.Pedido', 'U') IS NOT NULL DROP TABLE LOS_GESTORES.Pedido;
IF OBJECT_ID('LOS_GESTORES.Detalle_Compra', 'U') IS NOT NULL DROP TABLE LOS_GESTORES.Detalle_Compra;
IF OBJECT_ID('LOS_GESTORES.Compra', 'U') IS NOT NULL DROP TABLE LOS_GESTORES.Compra;
IF OBJECT_ID('LOS_GESTORES.Sillon', 'U') IS NOT NULL DROP TABLE LOS_GESTORES.Sillon;
IF OBJECT_ID('LOS_GESTORES.Madera', 'U') IS NOT NULL DROP TABLE LOS_GESTORES.Madera;
IF OBJECT_ID('LOS_GESTORES.Tela', 'U') IS NOT NULL DROP TABLE LOS_GESTORES.Tela;
IF OBJECT_ID('LOS_GESTORES.Relleno', 'U') IS NOT NULL DROP TABLE LOS_GESTORES.Relleno;
IF OBJECT_ID('LOS_GESTORES.Proveedor', 'U') IS NOT NULL DROP TABLE LOS_GESTORES.Proveedor;
IF OBJECT_ID('LOS_GESTORES.Cliente', 'U') IS NOT NULL DROP TABLE LOS_GESTORES.Cliente;
IF OBJECT_ID('LOS_GESTORES.Sillon_Modelo', 'U') IS NOT NULL DROP TABLE LOS_GESTORES.Sillon_Modelo;
IF OBJECT_ID('LOS_GESTORES.Sillon_Medida', 'U') IS NOT NULL DROP TABLE LOS_GESTORES.Sillon_Medida;
IF OBJECT_ID('LOS_GESTORES.Material', 'U') IS NOT NULL DROP TABLE LOS_GESTORES.Material;
IF OBJECT_ID('LOS_GESTORES.Sucursal', 'U') IS NOT NULL DROP TABLE LOS_GESTORES.Sucursal;
IF OBJECT_ID('LOS_GESTORES.Localidad', 'U') IS NOT NULL DROP TABLE LOS_GESTORES.Localidad;
IF OBJECT_ID('LOS_GESTORES.Provincia', 'U') IS NOT NULL DROP TABLE LOS_GESTORES.Provincia;

PRINT 'Tablas eliminadas.';
GO

-- 4. Eliminar el esquema

PRINT 'Eliminando Esquema LOS_GESTORES';
IF SCHEMA_ID('LOS_GESTORES') IS NOT NULL
BEGIN
    DROP SCHEMA LOS_GESTORES;
    PRINT 'Esquema LOS_GESTORES eliminado.';
END
GO

PRINT 'Eliminacion de estructuras completada.';