 SELECT COMPRA_SUCURSAL SUCURSAL
	,YEAR(COMPRA_FECHA) ANIO
	,MONTH(COMPRA_FECHA) MES
	,SUM(COMPRA_TOTAL) TOTAL
 INTO BI.COMPRAS
 FROM LOS_GESTORES.COMPRA
 GROUP BY
	 COMPRA_SUCURSAL
	,YEAR(COMPRA_FECHA)
	,MONTH(COMPRA_FECHA)



