
SELECT COMPRA_SUCURSAL SUCURSAL
	, LOS_GESTORES.bi_gettiempoid(compra_fecha)
	, SUM(COMPRA_TOTAL) TOTAL
	, COUNT(*) CANTIDAD
-- INTO BI.COMPRAS
FROM LOS_GESTORES.COMPRA
GROUP BY
	 COMPRA_SUCURSAL
	,LOS_GESTORES.bi_gettiempoid(compra_fecha)



