 SELECT FACTURA_SUCURSAL SUCURSAL
	,YEAR(FACTURA_FECHA) ANIO
	,MONTH(FACTURA_FECHA) MES
	,SUM(FACTURA_TOTAL) TOTAL
 INTO BI.FACTURACION
 FROM LOS_GESTORES.FACTURA
 GROUP BY
	 FACTURA_SUCURSAL
	,YEAR(FACTURA_FECHA)
	,MONTH(FACTURA_FECHA)



