CREATE VIEW BI.PUNTO1 AS
SELECT F.SUCURSAL,F.ANIO,F.MES,ISNULL(F.TOTAL,0) - ISNULL(C.TOTAL,0) GANANCIA 
FROM BI.FACTURACION F
FULL JOIN BI.COMPRAS C ON F.SUCURSAL = C.SUCURSAL
	AND F.ANIO = C.ANIO
	AND F.MES = C.MES


