CREATE FUNCTION BI.getModeloTopVentas (@anio INT, @CUATRIMESTRE INT, @RANGO NVARCHAR(6), @LOCALIDAD INT, @POSICION INT)
RETURNS BIGINT
AS
BEGIN
	
	DECLARE @MODELO BIGINT
	DECLARE TOPVENTAS CURSOR FOR
	SELECT TOP 3 SILLON_MODELO 
	FROM BI.VENTAS_POR_MODELO
		WHERE ANIO = @ANIO
		AND CUATRIMESTRE = @CUATRIMESTRE
		AND RANGO_ETAREO = @RANGO
		AND SUCURSAL_LOCALIDAD = @LOCALIDAD
		GROUP BY SILLON_MODELO
		ORDER BY SUM(TOTAL_VENTAS) DESC 


	OPEN TOPVENTAS
	WHILE (@POSICION>0)
	BEGIN
		FETCH NEXT FROM TOPVENTAS INTO @MODELO
		SET @POSICION = @POSICION -1
	END
	
    CLOSE TOPVENTAS
    DEALLOCATE TOPVENTAS
	RETURN @MODELO
END
GO
