 SELECT 
	 SILLON_MODELO_CODIGO SILLON_MODELO
	,SUCURSAL_LOCALIDAD
	,YEAR(FACTURA_FECHA) ANIO
	,bi.getcuatrimestre(FACTURA_FECHA) CUATRIMESTRE
	,bi.getRangoEtario(CLIENTE_FECHANACIMIENTO,FACTURA_FECHA) RANGO_ETAREO
	,SUM(DETALLE_PEDIDO_CANTIDAD * DETALLE_PEDIDO_PRECIO) TOTAL_VENTAS
	INTO BI.VENTAS_POR_MODELO
 
 FROM LOS_GESTORES.FACTURA
 JOIN LOS_GESTORES.CLIENTE ON FACTURA_CLIENTE = CLIENTE_ID
 JOIN LOS_GESTORES.DETALLE_PEDIDO ON FACTURA_PEDIDO = DETALLE_PEDIDO_NUMERO
 JOIN LOS_GESTORES.SILLON ON DETALLE_PEDIDO_SILLON_CODIGO = SILLON_CODIGO
 JOIN LOS_GESTORES.SUCURSAL ON FACTURA_SUCURSAL = SUCURSAL_NROSUCURSAL

 GROUP BY
	 SILLON_MODELO_CODIGO
	,SUCURSAL_LOCALIDAD
	,YEAR(FACTURA_FECHA)
	,bi.getcuatrimestre(FACTURA_FECHA) 
	,bi.getRangoEtario(CLIENTE_FECHANACIMIENTO,FACTURA_FECHA) 
