SELECT ANIO
	,FLOOR((MES+3)/4) CUATRIMESTRE
	,PEDIDO_SUCURSAL
	,pedido_estado
	,100 * SUM(CANTIDAD) /
	(SELECT SUM(CANTIDAD) FROM BI.PEDIDOS
		WHERE  ANIO = P1.ANIO
		AND FLOOR((MES+3)/4) = FLOOR((P1.MES+3)/4) 
		AND PEDIDO_SUCURSAL = P1.PEDIDO_SUCURSAL) PORCENTAJE

FROM BI.PEDIDOS P1
GROUP BY  ANIO
	,FLOOR((MES+3)/4) 
	,PEDIDO_SUCURSAL
	,pedido_estado
