SELECT 'DROP TABLE ' + SCHEMA_NAME(schema_id) +'.' + NAME  FROM SYS.objects
WHERE TYPE = 'U' AND SCHEMA_NAME(schema_id) = 'LOS_GESTORES'
AND NAME LIKE 'BI%'
ORDER BY create_date DESC
GO

DROP TABLE LOS_GESTORES.BI_modelo
DROP TABLE LOS_GESTORES.BI_material
DROP TABLE LOS_GESTORES.BI_estado_pedido
DROP TABLE LOS_GESTORES.BI_turno
DROP TABLE LOS_GESTORES.BI_tiempo
DROP TABLE LOS_GESTORES.BI_sucursal
DROP TABLE LOS_GESTORES.BI_proveedor
DROP TABLE LOS_GESTORES.BI_cliente
DROP TABLE LOS_GESTORES.BI_ubicacion