/*
SELECT 'DROP TABLE ' + SCHEMA_NAME(schema_id) +'.' + NAME  FROM SYS.objects
WHERE TYPE = 'U' AND SCHEMA_NAME(schema_id) = 'LOS_GESTORES'
AND NAME LIKE 'BI%'
ORDER BY create_date DESC
GO
*/


DROP TABLE LOS_GESTORES.BI_HECHO_ENVIO
DROP TABLE LOS_GESTORES.BI_HECHO_MATERIAL
DROP TABLE LOS_GESTORES.BI_HECHO_FABRICACION
DROP TABLE LOS_GESTORES.BI_HECHO_PEDIDO
DROP TABLE LOS_GESTORES.BI_HECHO_VENTA
DROP TABLE LOS_GESTORES.BI_HECHO_COMPRA
DROP TABLE LOS_GESTORES.BI_HECHO_FACTURA
DROP TABLE LOS_GESTORES.BI_modelo
DROP TABLE LOS_GESTORES.BI_estado_pedido
DROP TABLE LOS_GESTORES.BI_material
DROP TABLE LOS_GESTORES.BI_turno
DROP TABLE LOS_GESTORES.BI_tiempo
DROP TABLE LOS_GESTORES.BI_proveedor
DROP TABLE LOS_GESTORES.BI_sucursal
DROP TABLE LOS_GESTORES.BI_cliente
DROP TABLE LOS_GESTORES.BI_ubicacion

GO

/*
SELECT 'DROP FUNCTION ' + SCHEMA_NAME(schema_id) +'.' + NAME 
FROM SYS.all_objects
WHERE TYPE = 'FN' AND SCHEMA_NAME(schema_id) = 'LOS_GESTORES'
*/
GO

DROP FUNCTION LOS_GESTORES.BI_GetTiempoID
DROP FUNCTION LOS_GESTORES.BI_getCuatrimestre
DROP FUNCTION LOS_GESTORES.BI_getEstadoPedidoId
DROP FUNCTION LOS_GESTORES.BI_getTurnoVenta
DROP FUNCTION LOS_GESTORES.BI_getMATERIALId
DROP FUNCTION LOS_GESTORES.BI_getRangoEtario

GO
/*
SELECT 'DROP VIEW ' + SCHEMA_NAME(schema_id) +'.' + NAME 
FROM SYS.all_objects
WHERE TYPE = 'V' AND SCHEMA_NAME(schema_id) = 'LOS_GESTORES'
GO
*/
DROP VIEW LOS_GESTORES.BI_V04_volumen_pedidos_por_turno_sucursal_mes_anio
DROP VIEW LOS_GESTORES.BI_V01_ganancias_mensuales_por_sucursal
DROP VIEW LOS_GESTORES.BI_volumen_pedidos_por_turno_sucursal_mes_anio
DROP VIEW LOS_GESTORES.BI_V05_conversion_pedidos_por_estado_cuatrimestre_sucursal
DROP VIEW LOS_GESTORES.BI_V06_tiempo_promedio_fabricacion_sucursal_cuatrimestre
DROP VIEW LOS_GESTORES.BI_V07_promedio_compras_mensual
DROP VIEW LOS_GESTORES.BI_V08_compras_por_tipo_material_sucursal_cuatrimestre
DROP VIEW LOS_GESTORES.BI_V09_porcentaje_cumplimiento_envios_mensual
DROP VIEW LOS_GESTORES.BI_V10_top_3_localidades_mayor_costo_envio

GO