SELECT SUCURSAL_NROSUCURSAL SUCURSAL_NRO,
	LOCALIDAD_ID,
	PROVINCIA_ID,
	LOCALIDAD_DESCRIPCION,
	PROVINCIA_DESCRIPCION

	INTO BI.SUCURSAL


FROM LOS_GESTORES.SUCURSAL
JOIN LOS_GESTORES.LOCALIDAD ON SUCURSAL_LOCALIDAD = LOCALIDAD_ID
JOIN LOS_GESTORES.PROVINCIA ON LOCALIDAD_PROVINCIA = PROVINCIA_ID